EPERM =	1	# Not super-user			
ENOENT =	2	# No such file or directory		
ESRCH =	3	# No such process			
EINTR =	4	# interrupted system call		
EIO =	5	# I/O error				
ENXIO =	6	# No such device or address		
E2BIG =	7	# Arg list too long			
ENOEXEC =	8	# Exec format error			
EBADF =	9	# Bad file number			
ECHILD =	10	# No children				
EAGAIN =	11	# Resource temporarily unavailable	
ENOMEM =	12	# Not enough core			
EACCES =	13	# Permission denied			
EFAULT =	14	# Bad address				
ENOTBLK =	15	# Block device required		
EBUSY =	16	# Mount device busy			
EEXIST =	17	# File exists				
EXDEV =	18	# Cross-device link			
ENODEV =	19	# No such device			
ENOTDIR =	20	# Not a directory			
EISDIR =	21	# Is a directory			
EINVAL =	22	# Invalid argument			
ENFILE =	23	# File table overflow			
EMFILE =	24	# Too many open files			
ENOTTY =	25	# Inappropriate ioctl for device	
ETXTBSY =	26	# Text file busy			
EFBIG =	27	# File too large			
ENOSPC =	28	# No space left on device		
ESPIPE =	29	# Illegal seek				
EROFS =	30	# Read only file system		
EMLINK =	31	# Too many links			
EPIPE =	32	# Broken pipe				
EDOM =	33	# Math arg out of domain of func	
ERANGE =	34	# Math result not representable	
ENOMSG =	35	# No message of desired type		
EIDRM =	36	# Identifier removed			
ECHRNG =	37	# Channel number out of range		
EL2NSYNC = 38	# Level 2 not synchronized		
EL3HLT =	39	# Level 3 halted			
EL3RST =	40	# Level 3 reset			
ELNRNG =	41	# Link number out of range		
EUNATCH = 42	# Protocol driver not attached		
ENOCSI =	43	# No CSI structure available		
EL2HLT =	44	# Level 2 halted			
EDEADLK =	45	# Deadlock condition.			
ENOLCK =	46	# No record locks available.		
ECANCELED = 47	# Operation canceled			
ENOTSUP =	48	# Operation not supported		